include:
  - ./backend/compose.prod.yml

services:
  client_web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.web
    volumes:
      - shared-volume:/app/dist

  client_mobile:
    build:
      context: ./frontend
      dockerfile: Dockerfile.mobile
    command: cp /workdir/android/app/build/outputs/apk/release/app-release-signed.apk /static/client.apk
    volumes:
      - shared-volume:/static
    depends_on:
      - client_web

  nginx:
    image: nginx:alpine
    volumes:
      - shared-volume:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - backend
      - client_web
    networks:
      - app-network

volumes:
  shared-volume:
