services:
  backend:
    build:
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:17
    env_file:
      - .env
